spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CardServiceGradle
    username: postgres
    password: Zhenya123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
